### ISSUE TITLE
models文件夹下缺少文件visualtransformermodel

### ISSUE THREAD

**Issue by PKUHaoWang** [xiaobaishu0097/ICLR_VTNet#6]
我在运行代码时出现了以下错误，请问这个代码文件在哪里

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from utils.class_finder import model_class, agent_class, optimizer_class
  File "/ddn/wanghao/ICLR_VTNet/utils/class_finder.py", line 1, in <module>
    import models
  File "/ddn/wanghao/ICLR_VTNet/models/__init__.py", line 3, in <module>
    from .pretrainedvisualtransformer import PreTrainedVisualTransformer
  File "/ddn/wanghao/ICLR_VTNet/models/pretrainedvisualtransformer.py", line 13, in <module>
    from .visualtransformermodel import VisualTransformer, get_gloabal_pos_embedding
ModuleNotFoundError: No module named 'models.visualtransformermodel'

**Comment by LazySapphire** [comment]
请问如何解决？我也不知道上哪儿去找这么个函数呢？

**Comment by PKUHaoWang** [comment]
> 请问如何解决？我也不知道上哪儿去找这么个函数呢？

vtnetmodel.py 中有 VisualTransformer, get_gloabal_pos_embedding，改一下 import 的文件试试

**Comment by LazySapphire** [comment]
> > 请问如何解决？我也不知道上哪儿去找这么个函数呢？
> 
> vtnetmodel.py 中有 VisualTransformer, get_gloabal_pos_embedding，改一下 import 的文件试试

好的，谢谢～ 我试试
